################################################################################
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
#  RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
#  CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
#  CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
################################################################################

IF(NOT BRLCAD_MOOSE_DIR)
    MESSAGE(WARNING "BRLCAD_MOOSE_DIR not set")
ENDIF(NOT BRLCAD_MOOSE_DIR)

IF(CMAKE_LINK_LIBRARY_SUFFIX)
    FIND_PATH(BRLCAD_MOOSE_LIBRARY_DIR NAMES "brlcad${CMAKE_LINK_LIBRARY_SUFFIX}" "libbrlcad${CMAKE_LINK_LIBRARY_SUFFIX}" PATHS ${BRLCAD_MOOSE_DIR} PATH_SUFFIXES lib libs bin)
ELSE(CMAKE_LINK_LIBRARY_SUFFIX)
    FIND_PATH(BRLCAD_MOOSE_LIBRARY_DIR NAMES "brlcad${CMAKE_SHARED_LIBRARY_SUFFIX}" "libbrlcad${CMAKE_SHARED_LIBRARY_SUFFIX}" PATHS ${BRLCAD_MOOSE_DIR} PATH_SUFFIXES lib libs bin)
ENDIF(CMAKE_LINK_LIBRARY_SUFFIX)

FIND_PATH(BRLCAD_MOOSE_INCLUDE_DIR "brlcad" PATHS ${BRLCAD_MOOSE_DIR} NO_SYSTEM_PATH PATH_SUFFIXES include)

FIND_LIBRARY(BRLCAD_MOOSE_LIBRARY NAMES brlcad PATHS ${BRLCAD_MOOSE_LIBRARY_DIR} NO_SYSTEM_PATH)

IF(BRLCAD_MOOSE_LIBRARY AND BRLCAD_MOOSE_INCLUDE_DIR)
    SET(BRLCAD_MOOSE_FOUND TRUE)
ENDIF(BRLCAD_MOOSE_LIBRARY AND BRLCAD_MOOSE_INCLUDE_DIR)
