################################################################################
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
#  RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
#  CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
#  CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
################################################################################

IF(NOT BRLCAD_DIR)
    MESSAGE(WARNING "BRLCAD_DIR not set")
ENDIF(NOT BRLCAD_DIR)

IF(CMAKE_LINK_LIBRARY_SUFFIX)
    FIND_PATH(BRLCAD_QTCAD_LIBRARY_DIR NAMES "qtcad${CMAKE_LINK_LIBRARY_SUFFIX}" "libqtcad${CMAKE_LINK_LIBRARY_SUFFIX}" PATHS ${BRLCAD_DIR} NO_SYSTEM_PATH PATH_SUFFIXES lib libs bin)
ELSE(CMAKE_LINK_LIBRARY_SUFFIX)
    FIND_PATH(BRLCAD_QTCAD_LIBRARY_DIR NAMES "qtcad${CMAKE_SHARED_LIBRARY_SUFFIX}" "libqtcad${CMAKE_SHARED_LIBRARY_SUFFIX}" PATHS ${BRLCAD_DIR} NO_SYSTEM_PATH PATH_SUFFIXES lib libs bin)
ENDIF(CMAKE_LINK_LIBRARY_SUFFIX)

FIND_PATH(BRLCAD_INCLUDE_DIR "brlcad" PATHS ${BRLCAD_DIR} NO_SYSTEM_PATH PATH_SUFFIXES include)
CMAKE_PATH(SET BRLCAD_INCLUDE_DIR "${BRLCAD_INCLUDE_DIR}/brlcad")

FIND_PATH(BRLCAD_OPENNURBS_INCLUDE_DIR "OpenNURBS" PATHS ${BRLCAD_DIR} NO_SYSTEM_PATH PATH_SUFFIXES include)
CMAKE_PATH(SET BRLCAD_OPENNURBS_INCLUDE_DIR "${BRLCAD_OPENNURBS_INCLUDE_DIR}/OpenNURBS")

FIND_LIBRARY(BRLCAD_QTCAD_LIBRARY NAMES qtcad PATHS ${BRLCAD_QTCAD_LIBRARY_DIR} NO_SYSTEM_PATH)

IF(BRLCAD_QTCAD_LIBRARY AND BRLCAD_INCLUDE_DIR AND BRLCAD_OPENNURBS_INCLUDE_DIR)
    SET(BRLCAD_FOUND TRUE)
ENDIF(BRLCAD_QTCAD_LIBRARY AND BRLCAD_INCLUDE_DIR AND BRLCAD_OPENNURBS_INCLUDE_DIR)
